steps:
  # Setup
  - name: node:12
    entrypoint: yarn
    args: ['install']
  #   env:
  #     - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
  # Build app
  - name: node:12
    entrypoint: yarn
    args: ['build:all:production']
    timeout: 1200s
  # Build images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/contributors-img/api:production', 'dist/apps/api']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/contributors-img/api:production']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'api-production', '--image', 'gcr.io/contributors-img/api:production', '--region', 'us-west1', '--platform', 'managed', '--allow-unauthenticated']
images:
  - gcr.io/contributors-img/api:production
timeout: 6000s