name: Create Release PR

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: 'main'
          PULL_REQUEST_BRANCH: 'production'
          PULL_REQUEST_TITLE: 'release'
          PULL_REQUEST_BODY: 'Preview: ![](https://stg.contrib.rocks/image?repo=angular/angular-ja)'
