name: Create Release PR

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request-action
      uses: vsoch/pull-request-action@1.0.18
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_PREFIX: "master"
        PULL_REQUEST_BRANCH: "production"
        PULL_REQUEST_TITLE: "release"

