name: Test

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install dependencies
      run: |
        yarn install
        npm --prefix functions ci

    - name: Copy .env
      run: npm --prefix functions run env:local

    - name: Build, and test
      run: |
        yarn build:prod
        yarn lint
        yarn test:ci
        npm --prefix functions run build
        npm --prefix functions run lint
