name: Test

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - run: yarn install
    - run: yarn lint
    - run: yarn test:all 
      env:
        CI: true
    - run: yarn build:all:production
